pages:
  stage: deploy
  image: archlinux/base:latest
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S lua lua-filesystem git
    - git clone --recursive https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/shagu/webls.git .webls

  script:
    - if ! [ -d content ]; then mkdir content; cp README.md content/; fi
    - cp -rf content .webls/content
    - ( cd .webls && ./webls.lua )
    - mv .webls/www public

  artifacts:
    paths:
    - public
